### ISSUE TITLE
User sessions & OIT authentication

### ISSUE THREAD

**Issue by bgoodwine** [NDEats/NDEats-Back-End#31]
Authenticate users by sending a request to OIT (send OIT a request, user sent to Okta system, returns false or the user's netid) 
> okta makes you log in every time to canvas on browser, BUT keeps you signed in on the canvas mobile app; we should figure out if Okta returns tokens that we can pass between backend/frontend to identify users

### Session management with Django
[This might be what we're trying to do](https://stackoverflow.com/questions/53832767/authentication-from-mobile-to-backend-django)
> "...so whenever you want to send a request to mobile you should provide that token (based on token authentication backend you choose) in your headers of request."

[django docs](https://docs.djangoproject.com/en/4.1/topics/http/sessions/)
[user sessions tutorial](https://developer.mozilla.org/en-US/docs/Learn/Server-side/Django/Sessions)
> HTTP is stateless > Django keeps track of state between site and a particular browser 

[user sessions for mobile](https://stackoverflow.com/questions/37316140/django-session-on-mobile-applications)

### Session management with React
[Tutorial](https://developer.okta.com/blog/2021/06/16/session-mgmt-react)

**Comment by bgoodwine** [comment]
Session variable, expiration date
[Using the Django authentication system](https://docs.djangoproject.com/en/4.1/topics/auth/default/)
[Customizing authentication in Django](https://docs.djangoproject.com/en/4.1/topics/auth/customizing/)

**Comment by jeanfboueri** [comment]
Note: Gonna work on this on branch called auth

**Comment by jeanfboueri** [comment]
Notes:
- If name in the request for user, we assume that we are creating a new user
- If name NOT in request for user, we assume the user is trying to login
- If the user is trying to login and the email doesn't exist within the database, we return id = 0
- If the user is trying to login and the email does exist within the database, we return id = user_id
- If the user is trying to signup we create a user entry and return the id associated with them as id = user_id
- If the user is trying to signup with an email that already exists, we return id = 0
