### ISSUE TITLE
Test with Postman (& command line testing instructions)

### ISSUE THREAD

**Issue by bgoodwine** [NDEats/NDEats-Back-End#6]
[Postman](https://www.postman.com/)
Test from command line:
1. Run server: `python3 manage.py runserver`
2. In another terminal, send post request: `curl -X POST -H "Content-Type: application/json" http://127.0.0.1:8000/orders/ -d "{\"dropoff\":\"Duncan Hall\",\"pickup\":\"Modern Market\",\"tip\":\"1\",\"ordererId\":\"1\",\"readyBy\":\"18:00:00\"}"`
4. Response received: `{"message": "Order created with ID: 2"}` (obviously ID will be different for each POST request)

**Comment by bgoodwine** [comment]
Update order to `curl -X PATCH http://127.0.0.1:8000/update-order/1 -d "{\"available\":\"0\"}"`

**Comment by jeanfboueri** [comment]
forget postman for now
